### PR TITLE
Allow for conversion of temperatures

### LINKED ISSUE #3: Cannot convert temperature units
Trying to convert temperature units (e.g. "70 degF to degC") results in a "No result" being displayed.
This seems to be the issue, with the relevant fix: https://github.com/hgrecco/pint/issues/386.

### PR DESCRIPTION
**Pull request by abraha2d**
Closes #3.

### CODE REVIEW

**Comment by noam09** [comment]
Thank you! 
Just a quick question: How will `autoconvert_offset_to_baseunit` affect units other than temperatures?

Also, I would prefer if units remain case-insensitive, unless there's a specific reason case should be kept as-is, such as with `degC`/`degF`. So maybe something like this:

```python
# Get query
term = (event.get_argument() or '')
case_units = ["degF", "degC"]
if not any(u in term for u in case_units):
    term = term.lower()
```

Would that work?

**Comment by abraha2d** [comment]
`autoconvert_offset_to_baseunit` should only affect units that are defined with offsets. Looking at the unit definition file, only temperature units have offsets (`degree_Celsius`, `degree_Rankine`, `degree_Fahrenheit`, and `degree_Reaumur` are all offset from `kelvin`).

As for the case-insensitivity, that works, but there are lots of other units/aliases that need capitalization as well. Maybe instead of lowercasing `term` at the very beginning, doing it at the last minute?
```python
        try:
            # print(Q_(src).to(dst))
            result = description = str(Q_(src.lower()).to(dst.lower()))
        except Exception as e:
            try:
                result = description = str(Q_(src).to(dst))
            except Exception as e:
                result = description = "No result"
```
The goal being to try the lowercased variant first, but if it doesn't work, then try with the original capitalization. I feel like the nested try/except is messy, though.

**Comment by noam09** [comment]
Hey, sorry for the delay, I've been busy with work. 

I guess that could work. An alternative approach may be to lookup the original (capitalized) string in the list of supported units, and fallback to `.lower()` if it isn't found. Not sure which of the two would be more efficient.

**Comment by abraha2d** [comment]
Np. Did some digging, and it looks like pint has case-insensitivity originating from https://github.com/hgrecco/pint/issues/105. See my latest commit.

Note: only the units are case-insensitive. Prefixes remain case sensitive, the argument being that there is a difference between Mm (megameters) and mm (millimeters).

**Comment by noam09** [comment]
@abraha2d thanks again for your contribution! Sorry it took a while.

**Pull request merged**
